language: ruby
cache:
  bundler: true
  directories:
    - ~/.rvm
before_install:
  - "echo 'gem: --no-rdoc --no-ri' > ~/.gemrc"
  - gem install bundler
matrix:
  include:
    - env: REDMINE_VERSION=3.4.2 VERBOSE=yes
      rvm: 1.9.3
      install:
        - gem install mime-types -v 2.99.3
        - bundle install --jobs=3 --retry=3
    - env: REDMINE_VERSION=3.4.2 VERBOSE=yes
      rvm: 2.0.0
    - env: REDMINE_VERSION=3.4.2 VERBOSE=yes
      rvm: 2.1
    - env: REDMINE_VERSION=3.4.2 VERBOSE=yes
      rvm: 2.2
    - env: REDMINE_VERSION=3.4.2 VERBOSE=yes
      rvm: 2.3
    - env: REDMINE_VERSION=3.4.2 VERBOSE=yes
      rvm: 2.4
    - env: REDMINE_VERSION=3.3.4 VERBOSE=yes
      rvm: 1.9.3
      install:
        - gem install mime-types -v 2.99.3
        - bundle install --jobs=3 --retry=3
    - env: REDMINE_VERSION=3.3.4 VERBOSE=yes
      rvm: 2.0.0
    - env: REDMINE_VERSION=3.3.4 VERBOSE=yes
      rvm: 2.1
    - env: REDMINE_VERSION=3.3.4 VERBOSE=yes
      rvm: 2.2
    - env: REDMINE_VERSION=3.3.4 VERBOSE=yes
      rvm: 2.3
    - env: REDMINE_VERSION=3.2.7 VERBOSE=yes
      rvm: 1.9.3
      install:
        - gem install mime-types -v 2.99.3
        - bundle install --jobs=3 --retry=3
    - env: REDMINE_VERSION=3.2.7 VERBOSE=yes
      rvm: 2.0.0
    - env: REDMINE_VERSION=3.2.7 VERBOSE=yes
      rvm: 2.1
    - env: REDMINE_VERSION=3.2.7 VERBOSE=yes
      rvm: 2.2

script:
  - export PLUGIN=redmine_mail_reminder
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./.travis-init.sh -r || exit 1
  - bash -x ./.travis-init.sh -i || exit 1
  - bash -x ./.travis-init.sh -u || exit 1
